### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luisrbferreira** [twentytwokhz/language-translator#17]
Hi! I'm getting the following error when trying to translate texts:

"The operation is not allowed because the subscription has exceeded its free quota."

**Comment by valenzine** [comment]
This is not a bug but expected behaviour: it's not unlimited. Get your own Azure API token and then set it up reading the [README.md](https://github.com/twentytwokhz/language-translator#readme) file

**Comment by gesantosur** [comment]
When I try to translate any text, that text disappears and no longer appears

**Comment by twentytwokhz** [comment]
@gesantosur that is now fixed with the latest **1.0.4** release

With regards to the initial text of the bug, @valenzine is correct:
You need to bring your own key in order to avoid exceeding the free quota.

My Azure quota for the free Translator service is `2M chars of any combination of standard translation`
